---
- name: Remove default users
  hosts: cloud_instance
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  remote_user: "{{ main_user }}"
  gather_facts: false
  vars_files:
    - vars.yml
  vars:
    ansible_ssh_user: "{{ main_user }}"
    ansible_become_pass: "{{ main_user_pass }}"

  tasks:
    - name: Delete default users and remove home directories
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: true
      loop: "{{ users_to_remove }}"